dist: xenial
sudo: false
latex: true
language: r
r: release

warnings_are_errors: false

cache:
  packages: true
  
apt_packages:
  - libgdal-dev
  - libudunits2-dev

r_packages:
  - rsconnect
  - shiny
  - tidyverse
  - kableExtra
  - e1071
  - smotefamily
  - ggplot2
  - ROCR
  - leaps
  - caTools
  - MASS
  - ROCR
  - mlr
  - FSelector
  - rpart
  - gbm
  - xgboost
  - ggplot2
  - ineq
  
script:
  - R -f deploy.R
