---
title: "Notice"
author: "ROBLIN Caroline, TELLIER Kevin, YE Maxime"
date: '`r format(Sys.time(), "%d %B %Y")`'
output: html_document


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
    
### Data presentation

We first have the dimension of the data table : first the number of observation and after the number of the variables.
We then made a significant test of the variables : first by information gain and after by chi-square test on each of the variables


###comparison of SVM and another model

####__Inputs__

#####_Model to compare with svm_
you can compare the SVM with :

* Logistic Regression
* Decision Tree
* Random Forest
* Gradient Boosting
* XGBoost

you have just to select the model with you would compare. Parameters of this model are already optimal


#####_SVM Kernel_
you can select your choice into the type of kernel :

* Linear
* Polynomial
* Radial Basis
* Sigmoid  

the best kernel is selected by default, and is the linear with optimate cost and gamma given by default but as a reminder if you would change that : C optimal is 25.8 and gamma optimal is 0.573

#####_Sample size (the larger the size chosen,the longer the processing time will be)_

For more rapidity is in 1,000 observationsin the begining, but you can vary that with the cursor

#####_C_

#####_Gamma_


#####__Outputs__
you could observe following

* SVM : Gini coefficient
* SVM : confusion matrix
* SVM : good classification rate
* Selected model : Gini coefficient
* Selected model : Confusion matrix
* Selected model : good classification rate
* ROC Curve comparison between the SVM abd the selected model



###Comparison of each model's performance - ROC Curve

####__Inputs__

#####_Sample size (the larger the size chosen,the longer the processing time will be)_

For more rapidity is in 1,000 observationsin the begining, but you can vary that with the cursor

#####__Outputs__

You could observe the ROC Curve for each models with optimal parameters in the same graphic, and you can remark that it isn't easy to choose the best model regardless of the sample size because of the crossing. 